### ISSUE TITLE
Divide CRUD sample of React to some components.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/FrontendTemplates#11]
# Requirement
React enables to divide component.
So, try to divide React CRUD sample to some components.
- https://github.com/OpenTouryoProject/FrontendTemplates/blob/develop/SPA/React/react_template/src/components/CrudSample.js
- https://github.com/OpenTouryoProject/FrontendTemplates/blob/develop/SPA/React/redux_template/src/components/CrudSample.js

**Comment by daisukenishino2** [comment]
# This issue has been resolved.
However, we are working with Private repositories and this fix has not yet been merged.

### reference:
- 一年ぶりぐらいにReact+Reduxを触った話。 - OSSコンソーシアム
https://www.osscons.jp/jo1pfmic5-537/
