### ISSUE TITLE
Fetch API の中で、catch メソッドを使ったエラーハンドリングがない

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/FrontendTemplates#14]
react_template や redux_template の中で、[fetch](https://github.com/OpenTouryoProject/FrontendTemplates/blob/develop/SPA/React/react_template/src/components/CrudSample.js#L331) メソッドが使われていますが、`catch` メソッドを使ったエラーハンドリングが必要だと思います。

現状の

```javascript
fetch(CrudSampleRootUrl + 'SelectCount', {method, headers, body})
    .then(response => response.json())
    .then(data =>  {
        if(data.Message)
        {
            this.setState({ message : data.Message });
        }
        else if(data.ErrorMSG)
        {
            this.setState({ message : JSON.stringify(data.ErrorMSG) });
        }
        else if(data.ExceptionMSG)
        {
            this.setState({ message : JSON.stringify(data.ExceptionMSG) });
        }
    });
```

では、バックエンド・サーバーから、レスポンスとして何かしらのエラーメッセージが返された場合はそのメッセージが表示されますが、HTTP 404 エラーなど、バックエンド・サーバーに到達できなかった場合は、何もエラーメッセージが表示されません。

**Comment by daisukenishino2** [comment]
@yusukemaegawa
以下を参考に修正しました。
https://github.com/github/fetch/issues/155#issuecomment-108353192
