### ISSUE TITLE
Add the CRUD sample to Vue template.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/FrontendTemplates#2]
# Requirement
Add the CRUD sample to Vue template.
Use the ASP.NET WebAPI at the server side.
- https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/CS/Samples/WS_sample/ASPNETWebService
- https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/CS/Samples4NetCore/Backend/ASPNETWebService

And, for [authentication use PKCE](16).

**Comment by daisukenishino2** [comment]
# Lists the HTTP telegrams.

## DataSet

### SelectCount

#### Request
https://localhost:44335/api/json/SelectCount

ddlDap=SQL&ddlMode1=individual&ddlMode2=static&ddlExRollback=-

#### Response
```JSON
{"message":"3件のデータがあります"}
```

### SelectAll_DT

#### Request
https://localhost:44335/api/json/SelectAll_DT

ddlDap=SQL&ddlMode1=individual&ddlMode2=static&ddlExRollback=-

#### Response
```JSON
{
    "message": "",
    "result": [
        {
            "shipperID": "1",
            "companyName": "Speedy Express",
            "phone": "(503) 555-9831"
        },
        {
            "shipperID": "2",
            "companyName": "United Package",
            "phone": "(503) 555-3199"
        },
        {
            "shipperID": "3",
            "companyName": "Federal Shipping",
            "phone": "(503) 555-9930"
        }
    ]
}
```

## CRUD

### Select

#### Request
https://localhost:44335/api/json/Select

```JSON
{
    "ddlDap": "SQL",
    "ddlMode1": "individual",
    "ddlMode2": "static",
    "ddlExRollback": "-",
    "shipper": {
        "shipperID": "1",
        "companyName": "",
        "phone": ""
    }
}
```

#### Response
```JSON
{
    "message": "",
    "result": {
        "shipperID": "1",
        "companyName": "Speedy Express",
        "phone": "(503) 555-9831"
    }
}
```

### Insert
#### Request
https://localhost:44335/api/json/Insert
```JSON
{
    "ddlDap": "SQL",
    "ddlMode1": "individual",
    "ddlMode2": "static",
    "ddlExRollback": "-",
    "shipper": {
        "shipperID": "1",
        "companyName": "Speedy Express",
        "phone": "(503) 555-9831"
    }
}
```

#### Response
```JSON
{"message":"1件追加"}
```

### Select

#### Request
https://localhost:44335/api/json/Update
```JSON
{
    "ddlDap": "SQL",
    "ddlMode1": "individual",
    "ddlMode2": "static",
    "ddlExRollback": "-",
    "shipper": {
        "shipperID": "1",
        "companyName": "Speedy Express",
        "phone": "(503) 555-9831"
    }
}
```

#### Response
```JSON
{"message":"1件更新"}
```

### Select
#### Request
#### Response
